tests for client, healthcheck, improve docker prod and size, other small fixes

diff --git a/client/Dockerfile b/client/Dockerfile
--- a/client/Dockerfile
+++ b/client/Dockerfile
@@ -1,9 +1,9 @@
-FROM node:22 AS base
+FROM node:22-alpine AS base
 WORKDIR /app
 COPY package*.json ./
 
 FROM base AS production
-RUN npm ci
+RUN npm ci --only=production
 COPY . .
 RUN npm run build
 EXPOSE 3000
@@ -11,5 +11,6 @@ CMD ["npm", "run", "start"]
 
 FROM base AS development
 RUN npm install
+COPY . .
 EXPOSE 3000
-CMD ["npm", "run", "dev"]
+CMD sh -c "npm run test && npm run dev || (echo 'Client tests failed!' && exit 1)"
diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -1,14 +1,15 @@
-FROM node:22 AS base
+FROM node:22-alpine AS base
 WORKDIR /app
 COPY package*.json ./
 
 FROM base AS development
 RUN npm install
+COPY . .
 EXPOSE 3002
-CMD ["npm", "run", "dev:start"]
+CMD sh -c "npm run test && npm run dev:start || (echo 'Server tests failed!' && exit 1)"
 
 FROM base AS production
-RUN npm ci
+RUN npm ci --only=production
 COPY . .
 EXPOSE 3002
 CMD ["npm", "run", "start"]
